// <auto-generated />
using System;
using Arena.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Arena.API.Migrations
{
    [DbContext(typeof(ArenaDbContext))]
    partial class ArenaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Arena.API.Models.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Persona")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ReputationScore")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("Arena.API.Models.Debate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("OpponentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProponentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("StartedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OpponentId");

                    b.HasIndex("ProponentId");

                    b.HasIndex("StartedByUserId");

                    b.ToTable("Debates");
                });

            modelBuilder.Entity("Arena.API.Models.DebateAggregate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AggregateDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DebateId")
                        .HasColumnType("uuid");

                    b.Property<double>("DiversityScore")
                        .HasColumnType("double precision");

                    b.Property<double>("EngagementScore")
                        .HasColumnType("double precision");

                    b.Property<double>("NoveltyScore")
                        .HasColumnType("double precision");

                    b.Property<double>("PenaltyScore")
                        .HasColumnType("double precision");

                    b.Property<double>("QualityScore")
                        .HasColumnType("double precision");

                    b.Property<int>("ReactionCount")
                        .HasColumnType("integer");

                    b.Property<double>("RecencyScore")
                        .HasColumnType("double precision");

                    b.Property<double>("RelevanceScore")
                        .HasColumnType("double precision");

                    b.Property<double>("ReputationScore")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalScore")
                        .HasColumnType("double precision");

                    b.Property<int>("ViewCount")
                        .HasColumnType("integer");

                    b.Property<int>("VoteCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DebateId", "AggregateDate")
                        .IsUnique();

                    b.ToTable("DebateAggregates");
                });

            modelBuilder.Entity("Arena.API.Models.Reaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DebateId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("TurnId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DebateId");

                    b.HasIndex("TurnId");

                    b.HasIndex("UserId");

                    b.ToTable("Reactions");
                });

            modelBuilder.Entity("Arena.API.Models.Turn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DebateId")
                        .HasColumnType("uuid");

                    b.Property<int>("TurnNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("DebateId", "TurnNumber")
                        .IsUnique();

                    b.ToTable("Turns");
                });

            modelBuilder.Entity("Arena.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Arena.API.Models.Vote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DebateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VotedForAgentId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VotedForAgentId");

                    b.HasIndex("DebateId", "UserId")
                        .IsUnique();

                    b.ToTable("Votes");
                });

            modelBuilder.Entity("Arena.API.Models.Debate", b =>
                {
                    b.HasOne("Arena.API.Models.Agent", "Opponent")
                        .WithMany("DebatesAsOpponent")
                        .HasForeignKey("OpponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Arena.API.Models.Agent", "Proponent")
                        .WithMany("DebatesAsProponent")
                        .HasForeignKey("ProponentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Arena.API.Models.User", "StartedByUser")
                        .WithMany()
                        .HasForeignKey("StartedByUserId");

                    b.Navigation("Opponent");

                    b.Navigation("Proponent");

                    b.Navigation("StartedByUser");
                });

            modelBuilder.Entity("Arena.API.Models.DebateAggregate", b =>
                {
                    b.HasOne("Arena.API.Models.Debate", "Debate")
                        .WithMany()
                        .HasForeignKey("DebateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Debate");
                });

            modelBuilder.Entity("Arena.API.Models.Reaction", b =>
                {
                    b.HasOne("Arena.API.Models.Debate", "Debate")
                        .WithMany("Reactions")
                        .HasForeignKey("DebateId");

                    b.HasOne("Arena.API.Models.Turn", "Turn")
                        .WithMany("Reactions")
                        .HasForeignKey("TurnId");

                    b.HasOne("Arena.API.Models.User", "User")
                        .WithMany("Reactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Debate");

                    b.Navigation("Turn");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Arena.API.Models.Turn", b =>
                {
                    b.HasOne("Arena.API.Models.Agent", "Agent")
                        .WithMany("Turns")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arena.API.Models.Debate", "Debate")
                        .WithMany("Turns")
                        .HasForeignKey("DebateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Debate");
                });

            modelBuilder.Entity("Arena.API.Models.Vote", b =>
                {
                    b.HasOne("Arena.API.Models.Debate", "Debate")
                        .WithMany("Votes")
                        .HasForeignKey("DebateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arena.API.Models.User", "User")
                        .WithMany("Votes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Arena.API.Models.Agent", "VotedForAgent")
                        .WithMany()
                        .HasForeignKey("VotedForAgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Debate");

                    b.Navigation("User");

                    b.Navigation("VotedForAgent");
                });

            modelBuilder.Entity("Arena.API.Models.Agent", b =>
                {
                    b.Navigation("DebatesAsOpponent");

                    b.Navigation("DebatesAsProponent");

                    b.Navigation("Turns");
                });

            modelBuilder.Entity("Arena.API.Models.Debate", b =>
                {
                    b.Navigation("Reactions");

                    b.Navigation("Turns");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("Arena.API.Models.Turn", b =>
                {
                    b.Navigation("Reactions");
                });

            modelBuilder.Entity("Arena.API.Models.User", b =>
                {
                    b.Navigation("Reactions");

                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
