// <auto-generated />
using System;
using Civic.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Civic.API.Migrations
{
    [DbContext(typeof(CivicDbContext))]
    [Migration("20260523055936_AddBriefingConceptThinkDeeper")]
    partial class AddBriefingConceptThinkDeeper
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Civic.API.Models.Briefing", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AudienceLevel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Disagreement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Headline")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Institution")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("IssueOrder")
                        .HasColumnType("integer");

                    b.Property<string>("KeyConcept")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string[]>("RelatedConcepts")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("StrongestArgumentAgainst")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StrongestArgumentFor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary10Min")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary30")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary3Min")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[]>("Tags")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("ThinkDeeperQuestion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[]>("ValuesInConflict")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("WhatChanged")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[]>("WhereToGoNext")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("WhoActed")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WhyItMatters")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IssueOrder");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Briefings");
                });

            modelBuilder.Entity("Civic.API.Models.Concept", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("CommonMisunderstanding")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CurrentExample")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlainDefinition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[]>("RelatedConcepts")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TryItQuestion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[]>("WhereYouSeeIt")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("WhyItMatters")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Concepts");
                });

            modelBuilder.Entity("Civic.API.Models.Petition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<int>("SignatureCount")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .IsDescending();

                    b.ToTable("Petitions");
                });

            modelBuilder.Entity("Civic.API.Models.ThinkDeeper", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BuildYourViewPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CanBothBeTrue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstReactionPrompt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Issue")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("StrongestArgumentA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StrongestArgumentB")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[]>("Values")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("WhatSideAMayMiss")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WhatSideBMayMiss")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string[]>("WhatWouldChangeYourMind")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("ThinkDeepers");
                });

            modelBuilder.Entity("Civic.API.Models.Briefing", b =>
                {
                    b.OwnsMany("Civic.API.Models.BriefingWord", "WordsToKnow", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("BriefingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Definition")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.Property<string>("Term")
                                .IsRequired()
                                .HasMaxLength(120)
                                .HasColumnType("character varying(120)");

                            b1.HasKey("Id");

                            b1.HasIndex("BriefingId");

                            b1.ToTable("BriefingWordsToKnow", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BriefingId");
                        });

                    b.Navigation("WordsToKnow");
                });
#pragma warning restore 612, 618
        }
    }
}
